### PR TITLE
Change Favicon

### LINKED ISSUE #9: Change favicon
Right now we have a black square, I am sure we can find something more suitable for this blog ;)

### PR DESCRIPTION
**Pull request by zysim**
Closes: #9

### CODE REVIEW

**Comment by zysim** [comment]
@Nanoseb What do you think? ;)

**Comment by takluyver** [comment]
My 2c: nice icon, but lose the wave animation. I don't want any tab icon to be moving unless it's trying to notify me of something (and even then, it had better be important).

**Comment by zysim** [comment]
https://github.com/Maritime-Robotics-Student-Society/blog/pull/20/commits/62b235bd53b2cbdeb9bd9925fcaf4d480b6f37c7 And it's gone 🎉

**Comment by Nanoseb** [comment]
That looks nice, thanks!

**Pull request merged**
