### PR TITLE
Update NPM Dependencies

### LINKED ISSUE #11: Vulnerability in dependencies
Github shows the message "We found a potential security vulnerability in one of your dependencies."
Is there something that can be done about it?

@zysim do you want to have a look at this?

### PR DESCRIPTION
**Pull request by zysim**
Closes: #11

This PR should solve any warnings we get on vulnerable dependencies.

## Warning: This is still a WIP.

### CODE REVIEW

**Comment by zysim** [comment]
Updating `grunt` to `^1.0.4`, and `grunt-contrib-jshint` to `^2.1.0` solves a big majority of the dependency issues. However, three dev dependencies, `grunt-imgcompress`, `grunt-newer`, and `grunt-surround` needs `grunt` to be `~0.4.0`. I could fork these dependencies and work from there.

My output:
```
npm WARN grunt-imgcompress@0.1.2 requires a peer of grunt@~0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-newer@0.7.0 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-surround@0.1.0 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
```

**Comment by takluyver** [comment]
Forking them sounds like a lot of effort. I'd check whether we actually still need them (e.g. have they been folded into other packages), and are there newer alternatives which everyone now uses instead?

**Comment by zysim** [comment]
Yeah that's what I thought of too. @tsaoyu mind checking if we still need them? I'm going through them now myself too, but I may miss some things out.

**Comment by tsaoyu** [comment]
I don't know if we need it or not. I setup this blog using made-mistakes template and they  has updated the [packages list](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/package.json) to mitigate the security issue. Maybe worth to migrate to newer version.

**Comment by zysim** [comment]
I'll look at that this evening :+1:

**Comment by zysim** [comment]
Going through Made Mistakes, there really doesn't seem to be an easy way to fix these vulnerabilities. The [docs for that template itself](https://github.com/mmistakes/made-mistakes-jekyll#made-mistakes-source-code_) says that we'd need to rework quite a bit of it in order to publish it to Github Pages. Case in point, it has a few plugins in its Gemfile that isn't allowed in Pages. On top of this, I'm struggling to even get the repo to build on my machine haha.

**Comment by zysim** [comment]
I should also mention that the NPM updates isn't as simple as updating the `package.json` in Made Mistakes.

**Comment by takluyver** [comment]
If it's not straightforward, I'd say don't waste time on it. I still don't
think the vulnerabilities matter for a static site.

**Comment by zysim** [comment]
Yeah that's true. Just thought I'd be able to tackle it :P

**Pull request closed without merging**
